version: '3.9'

services:
  mongodb:
    image: mongo:6.0.4
    volumes:
      - ./.docker/mongodb:/data/db
      - ./etc:/etc/mongo
      # - ./etc-tls:/etc/mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    command: [ "mongod", "--config", "/etc/mongo/mongod.conf" ]
