net:
  port: 27017
  bindIp: 0.0.0.0
  # TLS
  tls:
    mode: requireTLS
    CAFile: /etc/mongo/localhost.crt
    certificateKeyFile: /etc/mongo/localhost.pem
    allowConnectionsWithoutCertificates: true 

security:
  authorization: enabled
  
storage:
  dbPath: /data/db
  journal:
    enabled: true
  wiredTiger:
    engineConfig:
      cacheSizeGB: 2
