user nginx;
worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80 default_server;
        server_name localhost;

        location / {
            root html;
            index index.html;
        }
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate ssl/localhost.crt;
        ssl_certificate_key ssl/localhost.key;

        location / {
            root html;
            index index.html;
        }
    }
}

