steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - | 
      gcloud functions deploy helloWorld  --trigger-http --allow-unauthenticated --runtime nodejs18 

# --region us-central1 --source .
