#!/bin/bash

docker exec -it informix bash -c "
  . /home/informix/.bashrc 2>/dev/null || true
  . /opt/ibm/informix/etc/informix.env 2>/dev/null || true
  export LANG=C
  export LC_ALL=C
   /opt/ibm/informix/bin/dbaccess db $@
"
