services:
  informix:
    image: icr.io/informix/informix-developer-database:14.10.FC9W1DE
    container_name: informix
    hostname: informix
    privileged: true
    environment:
      - LICENSE=accept
      - STORAGE=local
      - INIT_FILE=init.sql
    ports:
      - "9088:9088"
    volumes:
      - ./.docker/informix:/opt/ibm/data
      - ./informix-init:/opt/ibm/config
      - ./src:/home/informix/src
